export const siteConfig = {
  name: "DimkaQQ",
  title: "Full-Stack Developer",
  description:
    "Full-stack developer specializing in web & mobile applications, scalable backends, and seamless user experiences.",
  domain: "dimkaprojects.xyz",
  email: "altynbek.din@gmail.com",
  github: "https://github.com/DimkaQQ",
  telegram: "https://t.me/Dimka_Hum",
  available: true,
};

export const services = [
  {
    icon: "◈",
    color: "from-violet-500 to-purple-600",
    glow: "rgba(139,92,246,0.15)",
    tags: ["React", "Next.js", "TypeScript"],
  },
  {
    icon: "◉",
    color: "from-cyan-400 to-blue-600",
    glow: "rgba(34,211,238,0.15)",
    tags: ["React Native", "Expo"],
  },
  {
    icon: "⬡",
    color: "from-emerald-400 to-teal-600",
    glow: "rgba(52,211,153,0.15)",
    tags: ["Node.js", "Go", "GraphQL"],
  },
  {
    icon: "◆",
    color: "from-orange-400 to-red-500",
    glow: "rgba(251,146,60,0.15)",
    tags: ["PostgreSQL", "MongoDB", "Redis"],
  },
  {
    icon: "◌",
    color: "from-pink-400 to-rose-600",
    glow: "rgba(244,114,182,0.15)",
    tags: ["Figma", "Tailwind", "A11y"],
  },
  {
    icon: "◎",
    color: "from-amber-400 to-yellow-500",
    glow: "rgba(251,191,36,0.15)",
    tags: ["Docker", "AWS", "Vercel"],
  },
];

export const projects = [
  {
    id: "marketplace",
    name: "NexMarket",
    tags: ["Next.js", "PostgreSQL", "Stripe", "Redis", "TypeScript"],
    subdomain: "nexmarket",
    accentColor: "#8b5cf6",
    gradientFrom: "#4c1d95",
    gradientTo: "#7c3aed",
    year: "2024",
    status: "live",
  },
  {
    id: "taskflow",
    name: "TaskFlow",
    tags: ["React", "Node.js", "Socket.io", "MongoDB"],
    subdomain: "taskflow",
    accentColor: "#22d3ee",
    gradientFrom: "#0e4f6e",
    gradientTo: "#0891b2",
    year: "2024",
    status: "live",
  },
  {
    id: "dataviz",
    name: "DataLens",
    tags: ["React", "D3.js", "Python", "ClickHouse"],
    subdomain: "datalens",
    accentColor: "#34d399",
    gradientFrom: "#064e3b",
    gradientTo: "#047857",
    year: "2024",
    status: "live",
  },
  {
    id: "aitalk",
    name: "AITalk",
    tags: ["Next.js", "OpenAI", "LangChain", "Supabase"],
    subdomain: "aitalk",
    accentColor: "#fb923c",
    gradientFrom: "#7c2d12",
    gradientTo: "#c2410c",
    year: "2024",
    status: "live",
  },
  {
    id: "finpay",
    name: "FinPay",
    tags: ["React Native", "Node.js", "PostgreSQL", "JWT"],
    subdomain: "finpay",
    accentColor: "#f472b6",
    gradientFrom: "#831843",
    gradientTo: "#be185d",
    year: "2023",
    status: "live",
  },
  {
    id: "devops",
    name: "ShipIt",
    tags: ["Go", "Kubernetes", "Terraform", "Prometheus"],
    subdomain: "shipit",
    accentColor: "#fbbf24",
    gradientFrom: "#78350f",
    gradientTo: "#b45309",
    year: "2023",
    status: "live",
  },
];

export const techStack = [
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Go",
  "PostgreSQL",
  "Redis",
  "Docker",
  "Kubernetes",
  "AWS",
  "GraphQL",
  "React Native",
  "Tailwind CSS",
  "Prisma",
  "Supabase",
];
