export const siteConfig = {
  name: "Darian Mirelli",
  title: "Full-Stack Developer",
  description:
    "Full-stack developer specializing in web & mobile applications, scalable backends, and seamless user experiences.",
  domain: "dimkaprojects.xyz",
  email: "altynbek.din@gmail.com",
  github: "https://github.com/DarQQ",
  telegram: "https://t.me/Dimka_Hum",
  available: true,
};

export const services = [
  {
    icon: "◈",
    color: "from-violet-500 to-purple-600",
    glow: "rgba(139,92,246,0.15)",
    tags: ["React", "Next.js", "TypeScript"],
  },
  {
    icon: "◉",
    color: "from-cyan-400 to-blue-600",
    glow: "rgba(34,211,238,0.15)",
    tags: ["React Native", "Expo"],
  },
  {
    icon: "⬡",
    color: "from-emerald-400 to-teal-600",
    glow: "rgba(52,211,153,0.15)",
    tags: ["Node.js", "Go", "GraphQL"],
  },
  {
    icon: "◆",
    color: "from-orange-400 to-red-500",
    glow: "rgba(251,146,60,0.15)",
    tags: ["PostgreSQL", "MongoDB", "Redis"],
  },
  {
    icon: "◌",
    color: "from-pink-400 to-rose-600",
    glow: "rgba(244,114,182,0.15)",
    tags: ["Figma", "Tailwind", "A11y"],
  },
  {
    icon: "◎",
    color: "from-amber-400 to-yellow-500",
    glow: "rgba(251,191,36,0.15)",
    tags: ["Docker", "AWS", "Vercel"],
  },
];

export const projects = [
  {
    id: "dizeltrade",
    name: "DizelTrade",
    tags: ["FastAPI", "PostgreSQL", "JavaScript", "Python"],
    subdomain: "dizeltrade",
    accentColor: "#8b5cf6",
    gradientFrom: "#4c1d95",
    gradientTo: "#7c3aed",
    year: "2025",
    status: "live",
  },
  {
    id: "rentoworld",
    name: "RentoWorld",
    tags: ["HTML", "JavaScript", "CSS"],
    subdomain: "rentoworld",
    accentColor: "#22d3ee",
    gradientFrom: "#0e4f6e",
    gradientTo: "#0891b2",
    year: "2025",
    status: "live",
  },
  {
    id: "tradinglearn",
    name: "TradingLearn",
    tags: ["Next.js", "FastAPI", "PostgreSQL", "TypeScript"],
    subdomain: "tradinglearn",
    accentColor: "#34d399",
    gradientFrom: "#064e3b",
    gradientTo: "#047857",
    year: "2026",
    status: "live",
  },
  {
    id: "shipter",
    name: "Shipter",
    tags: ["Python", "HTML", "FastAPI"],
    subdomain: "shipter",
    accentColor: "#fb923c",
    gradientFrom: "#7c2d12",
    gradientTo: "#c2410c",
    year: "2025",
    status: "live",
  },
  {
    id: "storage",
    name: "Multi-Entity Procurement",
    tags: ["React", "TypeScript", "Tailwind", "Vite"],
    subdomain: "storage",
    accentColor: "#c8a84b",
    gradientFrom: "#3d2a00",
    gradientTo: "#7a5c14",
    year: "2026",
    status: "live",
  },
  {
    id: "caspianflow",
    name: "CaspianFlow",
    tags: ["Python", "FastAPI", "JavaScript", "Stripe"],
    subdomain: "caspianflow",
    accentColor: "#e8b84b",
    gradientFrom: "#04080f",
    gradientTo: "#0c1422",
    year: "2025",
    status: "live",
  },
  {
    id: "restaurant",
    name: "RestOS",
    tags: ["FastAPI", "HTMX", "PostgreSQL", "Python"],
    subdomain: "restaurant",
    accentColor: "#c8a84b",
    gradientFrom: "#1a0e00",
    gradientTo: "#3d2800",
    year: "2026",
    status: "live",
  },
  {
    id: "hr",
    name: "RestOS HR",
    tags: ["FastAPI", "Python", "SQLite", "PWA"],
    subdomain: "hr",
    accentColor: "#0a84ff",
    gradientFrom: "#001233",
    gradientTo: "#003380",
    year: "2026",
    status: "live",
  },
  {
    id: "botfactory",
    name: "BotFactory",
    tags: ["React", "TypeScript", "FastAPI", "Telegram"],
    subdomain: "botfactory",
    accentColor: "#2481cc",
    gradientFrom: "#001a33",
    gradientTo: "#003d7a",
    year: "2026",
    status: "live",
  },
];

export const techStack = [
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Go",
  "PostgreSQL",
  "Redis",
  "Docker",
  "Kubernetes",
  "AWS",
  "GraphQL",
  "React Native",
  "Tailwind CSS",
  "Prisma",
  "Supabase",
];
